/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-5dK60-Kw7dhJ0yM5bfiDJkZGDCaOzrcicL-iRHi2yOZk58xVwgQmoow2TYC5SLWooC-bR1v279au9cksI1xqgahEzN6zCRsoWEaAbTuFYj4Kao3nH3Ur75D1",
  "tt": "tt-1-kAKlOLYikDfuoRZOdLmt-IgoM1QHLZUNNE2-JkwBCRY=",
  "version": "2020-11-20"
}

export default ebconfig;